### ISSUE TITLE
No license included. An open-source license would be appreciated

### ISSUE THREAD

**Issue by atimholt** [aaronbieber/vim-vault#4]
I know this is an old plugin that hasn't been touched for years, but that's exactly why I, for one, would appreciate the inclusion of an open-source license. I've made [a personal fork](https://github.com/atimholt/vim-vault.git) which is of dubious legality until one is included.

If you just want to “throw” the plugin “into the wind”, as it were, you may just want to release it to public domain. [“The unlicense”](https://unlicense.org/) does essentially that, while also including a liability-limiting clause.

If you're into the philosophy of community-driven development, and want to make sure that any “tweaks” or “changes” remain under an open-source license, you'll probably want something like the GPL, ([here's v3](https://www.gnu.org/licenses/gpl-3.0.en.html)).

[The MIT license](https://opensource.org/licenses/MIT) is also a pretty good choice. It's mostly made to ensure that no one tries to pass off the code as entirely their own (they must retain your copyright notice and the license you've released it under). [Here are a bunch of variants](https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT).

Or, y'know, just license it however you want. Even just a statement in the readme or a “LICENSE” file stating that this project is not released under any open license and that you retain all rights would be useful (but would make it difficult for anyone to use the project for many purposes, needless to say).

I'm not a lawyer or anything, if that needs saying.

**Comment by aaronbieber** [comment]
This is indeed "abandonware," as I switched over to Emacs some years ago. Point taken, though, so I added the "Unlicense" to this project. I hope it's providing some value to you!
